import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import { Project } from "../types/pim";
import { renderOverview, renderArchitecture, renderSchema, renderTasks, renderDecisions, renderApiContract, renderContextPack, renderPerspectives, renderRoadmap } from "./markdown";
import { generateCursorRules, generateClaudeMd, generateAgentsMd } from "./agentRules";
import { generateAllContextPacks } from "../core/contextPack";
import { getProviderId, getEffectiveModel } from "../llm/provider";

export interface ExportResult {
  success: boolean;
  filesWritten: string[];
  errors: string[];
}

/**
 * Standard disclaimer appended to every generated plan document. Keeps the
 * "AI-assisted, verify-before-use" notice in front of users everywhere a plan
 * is written to disk.
 */
export const PLAN_DISCLAIMER = `---

*Disclaimer: Vizier is an AI-assisted planning aid. Generated plans are heuristic and may contain inaccuracies, omissions, or unsafe suggestions. They are NOT a substitute for professional engineering, security, legal, or product advice. Review, validate, and test all output before using it. AI output can be wrong — do not deploy unverified plans.*`;

/**
 * Write a plan document, appending the standard disclaimer footer.
 */
function writePlanFile(filePath: string, content: string) {
  fs.writeFileSync(filePath, content + "\n" + PLAN_DISCLAIMER + "\n", "utf8");
}

/**
 * Detect which AI tools are installed in the workspace.
 */
export function detectAITools(workspacePath: string): string[] {
  const tools: string[] = [];
  
  if (fs.existsSync(path.join(workspacePath, ".cursorrules"))) {
    tools.push("cursor");
  }
  if (fs.existsSync(path.join(workspacePath, ".cursor"))) {
    tools.push("cursor");
  }
  if (fs.existsSync(path.join(workspacePath, "CLAUDE.md"))) {
    tools.push("claude");
  }
  if (fs.existsSync(path.join(workspacePath, ".claude"))) {
    tools.push("claude");
  }
  if (fs.existsSync(path.join(workspacePath, ".windsurfrules"))) {
    tools.push("windsurf");
  }
  if (fs.existsSync(path.join(workspacePath, ".windsurf"))) {
    tools.push("windsurf");
  }
  
  return [...new Set(tools)];
}

/**
 * Export the full plan to files in the workspace.
 */
export async function exportPlan(project: Project): Promise<ExportResult> {
  const result: ExportResult = {
    success: true,
    filesWritten: [],
    errors: []
  };

  const workspaceFolders = vscode.workspace.workspaceFolders;
  if (!workspaceFolders || workspaceFolders.length === 0) {
    result.success = false;
    result.errors.push("No workspace folder open");
    return result;
  }

  const workspacePath = workspaceFolders[0].uri.fsPath;
  const planDir = path.join(workspacePath, "plan");
  const contextDir = path.join(planDir, "context");

  try {
    // Create directories
    if (!fs.existsSync(planDir)) {
      fs.mkdirSync(planDir, { recursive: true });
    }
    if (!fs.existsSync(contextDir)) {
      fs.mkdirSync(contextDir, { recursive: true });
    }

    // Write machine-readable plan (source of truth for progress monitoring)
    const planJsonPath = path.join(planDir, "plan.json");
    const projectWithMeta = {
      ...project,
      generated_by: {
        provider: getProviderId(),
        model: getEffectiveModel(),
        at: new Date().toISOString(),
        vizier: "0.1.0"
      }
    };
    fs.writeFileSync(planJsonPath, JSON.stringify(projectWithMeta, null, 2), "utf8");
    result.filesWritten.push("plan/plan.json");

    // Write overview (with provenance footer for traceability)
    const overviewPath = path.join(planDir, "overview.md");
    const provenance = `\n\n---\n\n*Generated by Vizier (provider: ${getProviderId()}, model: ${getEffectiveModel()}) on ${new Date().toLocaleString()}.*`;
    writePlanFile(overviewPath, renderOverview(project) + provenance);
    result.filesWritten.push("plan/overview.md");

    // Write architecture
    const archPath = path.join(planDir, "architecture.md");
    writePlanFile(archPath, renderArchitecture(project));
    result.filesWritten.push("plan/architecture.md");

    // Write schema
    const schemaPath = path.join(planDir, "schema.md");
    writePlanFile(schemaPath, renderSchema(project));
    result.filesWritten.push("plan/schema.md");

    // Write API contract
    const apiPath = path.join(planDir, "api.md");
    writePlanFile(apiPath, renderApiContract(project));
    result.filesWritten.push("plan/api.md");

    // Write tasks
    const tasksPath = path.join(planDir, "tasks.md");
    writePlanFile(tasksPath, renderTasks(project));
    result.filesWritten.push("plan/tasks.md");

    // Write decisions
    const decisionsPath = path.join(planDir, "decisions.md");
    writePlanFile(decisionsPath, renderDecisions(project));
    result.filesWritten.push("plan/decisions.md");

    // Write roadmap (if defined)
    if (project.roadmap) {
      const roadmapPath = path.join(planDir, "roadmap.md");
      writePlanFile(roadmapPath, renderRoadmap(project));
      result.filesWritten.push("plan/roadmap.md");
    }

    // Write expert perspectives (if any selected)
    if (project.perspectives && Object.keys(project.perspectives).length > 0) {
      const perspectivesPath = path.join(planDir, "perspectives.md");
      writePlanFile(perspectivesPath, renderPerspectives(project));
      result.filesWritten.push("plan/perspectives.md");
    }

    // Write context packs
    const contextPacks = generateAllContextPacks(project);
    for (const pack of contextPacks) {
      const packPath = path.join(contextDir, `${pack.task_id}.md`);
      writePlanFile(packPath, renderContextPack(pack.task_id, pack));
      result.filesWritten.push(`plan/context/${pack.task_id}.md`);
    }

    // Detect and write agent-specific rules
    const aiTools = detectAITools(workspacePath);
    
    if (aiTools.includes("cursor") || aiTools.length === 0) {
      const cursorRulesPath = path.join(workspacePath, ".cursorrules");
      fs.writeFileSync(cursorRulesPath, generateCursorRules(project), "utf8");
      result.filesWritten.push(".cursorrules");
    }
    
    if (aiTools.includes("claude")) {
      const claudeMdPath = path.join(workspacePath, "CLAUDE.md");
      writePlanFile(claudeMdPath, generateClaudeMd(project));
      result.filesWritten.push("CLAUDE.md");
    }
    
    // If no specific tool detected, write AGENTS.md as fallback
    if (aiTools.length === 0) {
      const agentsMdPath = path.join(workspacePath, "AGENTS.md");
      writePlanFile(agentsMdPath, generateAgentsMd(project));
      result.filesWritten.push("AGENTS.md");
    }

  } catch (error) {
    result.success = false;
    result.errors.push(error instanceof Error ? error.message : "Unknown error");
  }

  return result;
}
