import { Project, Product, Architecture, Entity, Task, Decision, Rule, ApiContract } from "../types/pim";

/**
 * Render the full project overview to markdown.
 */
export function renderOverview(project: Project): string {
  const p = project.product;
  return `# ${project.name}

## Vision

${p.vision}

## Target Audience

${p.target_audience}

## MVP Scope

${formatBulletList(p.mvp_scope)}

## Phase 2 Scope

${formatBulletList(p.phase2_scope)}

## Core Workflows

${p.core_workflows.map((w, i) => `${i + 1}. ${w}`).join("\n")}

${perspectivesSummary(project)}

---

*Generated by Vizier on ${new Date().toLocaleDateString()}*
`;
}

function perspectivesSummary(project: Project): string {
  const perspectives = project.perspectives;
  if (!perspectives || Object.keys(perspectives).length === 0) return "";
  const list = Object.values(perspectives).map((p) => `- ${p.label}`).join("\n");
  return `## Expert Perspectives

${list}

`;
}

/**
 * Render all selected expert-perspective sections to a single markdown doc.
 */
export function renderPerspectives(project: Project): string {
  const perspectives = project.perspectives;
  if (!perspectives || Object.keys(perspectives).length === 0) {
    return "# Expert Perspectives\n\nNo perspectives selected.";
  }

  let md = `# Expert Perspectives\n\n`;
  for (const id of Object.keys(perspectives)) {
    const p = perspectives[id];
    md += `## ${p.label} (${p.roleId})\n\n`;
    md += `${p.summary}\n\n`;

    if (p.recommendations.length > 0) {
      md += `### Recommendations\n\n`;
      md += `| Priority | Recommendation | Detail |\n`;
      md += `|---|---|---|\n`;
      for (const r of p.recommendations) {
        md += `| ${r.priority || "should"} | ${r.title} | ${r.detail} |\n`;
      }
      md += `\n`;
    }

    if (p.risks.length > 0) {
      md += `### Risks / Watch-outs\n\n`;
      for (const risk of p.risks) md += `- ${risk}\n`;
      md += `\n`;
    }

    if (p.open_questions.length > 0) {
      md += `### Open Questions\n\n`;
      for (const q of p.open_questions) md += `- ${q}\n`;
      md += `\n`;
    }

    md += `---\n\n`;
  }

  return md;
}

/**
 * Render the architecture section to markdown.
 */
export function renderArchitecture(project: Project): string {
  const a = project.architecture;
  if (!a) return "# Architecture\n\nNo architecture defined.";

  return `# Architecture

## Frontend

| Component | Choice |
|-----------|--------|
| Framework | ${a.frontend.framework} |
| UI Library | ${a.frontend.ui_library} |
| State Management | ${a.frontend.state_management} |
| Routing | ${a.frontend.routing} |

**Rationale:** ${a.rationale.frontend}

## Backend

| Component | Choice |
|-----------|--------|
| Runtime | ${a.backend.runtime} |
| Framework | ${a.backend.framework} |
| API Style | ${a.backend.api_style} |

**Rationale:** ${a.rationale.backend}

## Database

| Component | Choice |
|-----------|--------|
| Type | ${a.database.type} |
| ORM | ${a.database.orm} |
| Hosting | ${a.database.hosting} |

**Rationale:** ${a.rationale.database}

## Authentication

| Component | Choice |
|-----------|--------|
| Strategy | ${a.auth.strategy} |
| Provider | ${a.auth.provider} |

**Rationale:** ${a.rationale.auth}

## Storage

| Component | Choice |
|-----------|--------|
| Provider | ${a.storage.provider} |
| Type | ${a.storage.type} |

**Rationale:** ${a.rationale.storage}

## Infrastructure

| Component | Choice |
|-----------|--------|
| Hosting | ${a.infrastructure.hosting} |
| CI/CD | ${a.infrastructure.ci_cd} |

**Rationale:** ${a.rationale.infrastructure}

${renderConnections(a)}
`;
}

function renderConnections(a: Architecture): string {
  const c = a.connections;
  if (!c || (!c.modules?.length && !c.data_flow?.length && !c.cross_links?.length)) {
    return "";
  }

  const sections: string[] = [];

  if (c.modules?.length) {
    sections.push(`## Modules & Internal Structure

| Module | Kind | Purpose | Likely Files |
|--------|------|---------|--------------|
${c.modules
  .map(
    (m) =>
      `| ${escapePipe(m.name)} | ${escapePipe(m.kind)} | ${escapePipe(m.purpose)} | ${(m.files || []).map(escapePipe).join(", ")} |`
  )
  .join("\n")}
`);
  }

  if (c.data_flow?.length) {
    sections.push(`## Data Flow & Hand-offs

| From | To | What | Mechanism |
|------|-----|------|-----------|
${c.data_flow
  .map(
    (d) =>
      `| ${escapePipe(d.from)} | ${escapePipe(d.to)} | ${escapePipe(d.what)} | ${escapePipe(d.mechanism)} |`
  )
  .join("\n")}
`);
  }

  if (c.cross_links?.length) {
    sections.push(`## Cross-Connections

${c.cross_links.map((l) => `- **${escapePipe(l.source)}** ↔ **${escapePipe(l.target)}**: ${escapePipe(l.relationship)}`).join("\n")}
`);
  }

  return sections.join("\n");
}

function escapePipe(value: unknown): string {
  return String(value ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/**
 * Render the schema section to markdown.
 */
export function renderSchema(project: Project): string {
  const entities = project.entities;
  
  let md = `# Data Model\n\n`;
  
  for (const entity of entities) {
    md += `## ${entity.name} (${entity.id})\n\n`;
    md += `| Field | Type | Required | Unique | Indexed |\n`;
    md += `|-------|------|----------|--------|----------|\n`;
    
    for (const field of entity.fields) {
      md += `| ${field.name} | ${field.type} | ${field.required ? "Yes" : "No"} | ${field.unique ? "Yes" : "No"} | ${field.indexed ? "Yes" : "No"} |\n`;
    }
    
    if (entity.relationships.length > 0) {
      md += `\n**Relationships:**\n`;
      for (const rel of entity.relationships) {
        md += `- ${rel.type} → ${rel.target_entity}${rel.description ? ` (${rel.description})` : ""}\n`;
      }
    }
    
    md += `\n`;
  }
  
  return md;
}

/**
 * Render the tasks section to markdown.
 */
export function renderTasks(project: Project): string {
  const tasks = project.tasks;
  
  let md = `# Build Tasks\n\n`;
  md += `Total: ${tasks.length} tasks\n\n`;
  
  for (const task of tasks) {
    md += `## ${task.id}: ${task.title}\n\n`;
    md += `${task.description}\n\n`;
    
    if (task.depends_on.length > 0) {
      md += `**Depends on:** ${task.depends_on.join(", ")}\n\n`;
    }
    
    md += `**Acceptance Criteria:**\n`;
    for (const ac of task.acceptance_criteria) {
      md += `- [ ] ${ac}\n`;
    }
    
    md += `\n**Expected Files:**\n`;
    for (const file of task.files_expected) {
      md += `- \`${file}\`\n`;
    }
    
    const estimate = [
      `Effort: ${task.estimated_effort}`,
      task.estimated_hours ? `~${task.estimated_hours}h` : null,
      task.story_points ? `${task.story_points} pts` : null
    ].filter(Boolean).join(" · ");
    md += `\n**Estimate:** ${estimate}  ${task.task_type !== "feature" ? `· _${task.task_type}_` : ""}\n\n`;
    md += `---\n\n`;
  }
  
  return md;
}

/**
 * Render the API contract section to markdown.
 */
export function renderApiContract(project: Project): string {
  const contract = project.api_contract;
  if (!contract || !contract.endpoints || contract.endpoints.length === 0) {
    return "# API Contract\n\nNo API contract defined.";
  }

  let md = `# API Contract\n\n`;
  md += `Total: ${contract.endpoints.length} endpoints\n\n`;

  for (const ep of contract.endpoints) {
    md += `## ${ep.method.toUpperCase()} ${ep.path}\n\n`;
    md += `${ep.summary}\n\n`;
    if (ep.description) md += `${ep.description}\n\n`;
    md += `**Auth required:** ${ep.auth ? "Yes" : "No"}\n\n`;
    if (ep.tags && ep.tags.length > 0) {
      md += `**Tags:** ${ep.tags.join(", ")}\n\n`;
    }
    if (ep.request && typeof ep.request === "object") {
      md += `**Request:**\n\`\`\`json\n${JSON.stringify(ep.request, null, 2)}\n\`\`\`\n\n`;
    }
    if (ep.response && typeof ep.response === "object") {
      md += `**Response:**\n\`\`\`json\n${JSON.stringify(ep.response, null, 2)}\n\`\`\`\n\n`;
    }
    md += `---\n\n`;
  }

  if (contract.notes) {
    md += `## Notes\n\n${contract.notes}\n`;
  }

  return md;
}

/**
 * Render the decisions section to markdown.
 */
export function renderDecisions(project: Project): string {
  const decisions = project.decisions;
  
  let md = `# Decision Register\n\n`;
  
  for (const decision of decisions) {
    md += `## ${decision.id}: ${decision.topic}\n\n`;
    md += `**Chosen:** ${decision.chosen}\n\n`;
    
    if (decision.options.length > 0) {
      md += `**Options Considered:**\n\n`;
      for (const option of decision.options) {
        md += `### ${option.name}\n\n`;
        if (option.pros.length > 0) {
          md += `**Pros:**\n`;
          for (const pro of option.pros) md += `- ${pro}\n`;
          md += `\n`;
        }
        if (option.cons.length > 0) {
          md += `**Cons:**\n`;
          for (const con of option.cons) md += `- ${con}\n`;
          md += `\n`;
        }
      }
    }
    
    md += `**Rationale:** ${decision.rationale}\n\n`;
    
    if (decision.impacts.length > 0) {
      md += `**Impacts:** ${decision.impacts.join(", ")}\n\n`;
    }
    
    md += `---\n\n`;
  }
  
  return md;
}

/**
 * Render the production roadmap (master to-do list) to markdown.
 */
export function renderRoadmap(project: Project): string {
  const roadmap = project.roadmap;
  if (!roadmap) return "# Production Roadmap\n\nNo roadmap defined.";

  const phases = ["foundation", "core", "integration", "polish", "production"];
  const phaseLabel: Record<string, string> = {
    foundation: "Foundation & Scaffolding",
    core: "Core Features",
    integration: "Integration & Wiring",
    polish: "Polish, Testing & Docs",
    production: "Production & Launch"
  };

  let md = `# Production Roadmap — Master To-Do List

${roadmap.overview}

`;

  for (const phase of phases) {
    const items = roadmap.items.filter((i) => i.phase === phase);
    if (items.length === 0) continue;

    md += `## ${phaseLabel[phase]}\n\n`;
    md += `- [ ] **${items.length} items**\n\n`;

    for (const item of items) {
      const deps = item.depends_on.length > 0 ? ` *(requires: ${item.depends_on.join(", ")})*` : "";
      md += `### ☐ ${item.id} — ${item.title}${deps}\n\n`;
      md += `- **What:** ${item.what}\n`;
      if (item.where) md += `- **Where:** \`${item.where}\`\n`;
      if (item.target) md += `- **Connects to:** ${item.target}\n`;
      if (item.why) md += `- **Why:** ${item.why}\n`;
      if (item.best_practices) md += `- **Best practices:** ${item.best_practices}\n`;
      if (item.verification) md += `- **Verify by:** ${item.verification}\n`;
      md += `- **Effort:** ${item.effort}\n\n`;
    }
  }

  return md;
}

/**
 * Render a single context pack to markdown.
 */
export function renderContextPack(taskId: string, contextPack: any): string {
  let md = `# Context Pack: ${taskId}\n\n`;
  md += `${contextPack.summary}\n\n`;
  
  if (contextPack.requirements.length > 0) {
    md += `## Requirements\n\n`;
    for (const req of contextPack.requirements) {
      md += `- **${req.id}:** ${req.text}\n`;
    }
    md += `\n`;
  }
  
  if (contextPack.entities.length > 0) {
    md += `## Entities\n\n`;
    for (const entity of contextPack.entities) {
      md += `- **${entity.name}** (${entity.id})\n`;
    }
    md += `\n`;
  }
  
  if (contextPack.decisions.length > 0) {
    md += `## Decisions\n\n`;
    for (const decision of contextPack.decisions) {
      md += `- **${decision.id}:** ${decision.topic} → ${decision.chosen}\n`;
    }
    md += `\n`;
  }
  
  if (contextPack.files.length > 0) {
    md += `## Expected Files\n\n`;
    for (const file of contextPack.files) {
      md += `- \`${file}\`\n`;
    }
    md += `\n`;
  }
  
  if (contextPack.do_not.length > 0) {
    md += `## Do NOT\n\n`;
    for (const item of contextPack.do_not) {
      md += `- ⚠️ ${item}\n`;
    }
    md += `\n`;
  }
  
  return md;
}

function formatBulletList(text: string): string {
  if (!text) return "";
  const lines = text.split("\n").filter(l => l.trim());
  return lines.map(l => `- ${l.replace(/^[-*]\s*/, "").trim()}`).join("\n");
}
